### ISSUE TITLE
Merge branch 'trunk' into blabla

### ISSUE THREAD

**Issue by jandegr** [navit-gps/navit#868]
Hi,
I see many commits with as description `Merge branch 'trunk' into blabla`
Those clutter the history.

I am far from a git expert but I wonder if navit-gps has this option set 
https://help.github.com/en/articles/configuring-commit-rebasing-for-pull-requests

and from https://www.freecodecamp.org/news/an-introduction-to-git-merge-and-rebase-what-they-are-and-how-to-use-them-131b863785f/

> Rebases are how changes should pass from the top of the hierarchy downwards, and merges are how they flow back upwards

A recent sample without targetting the folks involved is https://github.com/navit-gps/navit/pull/859/files

A pretty simple change of 1 file.

but looking in the history https://github.com/navit-gps/navit/commits/trunk/navit
I see the word `baltic` 5 times

Up to now this can be seen as I am just splitting hairs, but I have the habbit of consulting a file's history often. I used to see all relevant changes very fast even back to the early days of Navit on sourceforge. In recent history that became less clear.
https://github.com/navit-gps/navit/commits/trunk/navit/maptool/osm.c

Thx

**Comment by metalstrolch** [comment]
Hmm, imho, this merging trunk into pull reqest branches is done, at least by me, because of two things. 

1. rebasing a branch requires force pushing which is considered impolite by most organisations as followers cannot just pull anymore and 
2. because github is configured to allow merge to trunk only if the branch is up to date and ci passed. That's the reason #860 was unmergeable without access to the branch. It was outdated. Github doesnt allow to rebase-merge then. So what other to do than to click "update branch" on the github pull request page whenever you hope to be ready to get your stuff in.

On merging of course I prefere a sqash merge over a rebase, as this way the feature branch boils down to one commit on trunk and trunks history is clean.

But that is just my opinion and no rule. If we think that force pushing is fine here, Ill happily rebase my public branches...

**Comment by metalstrolch** [comment]
At least for me, it seems I must learn squash merging on github, as it did indeed a merge commit the last times I merged my branches. 

Sorry for this, wasnt meant to be done that way. Mea culpa...

That's why I prefare command line usually, but that's gotten really hard to do with ci as well.

**Comment by lains** [comment]
So is squash merge is the way to go?
It seems quite easy on Github (I've done it twice already) and makes history more readble.
If so, shall we close this ticket?

**Comment by jkoan** [comment]
> So is squash merge is the way to go?

Yes, depending on what has been done. If there is only one commit which has the right commit format we can also rebase merge. 
Is the issue still continues we should probably revisit the content of https://navit.readthedocs.io/en/latest/development/commit_guidelines.html
But for now lets close this issue.
